service:
  name: landing-page-answers

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal
  region: eu-west-2
  stage: prod
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: arn:aws:dynamodb:eu-west-2:049681365170:table/landing-page-answers
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  storeAnswers:
    handler: handler.storeAnswers
    events:
      - http:
          method: post
          path: /answers
          cors: true
